spring:
  application:
    name: ms-ai-engine
  ai:
    anthropic:
      api-key: ${ANTHROPIC_API_KEY}
      chat:
        options:
          model: claude-sonnet-4-5
          temperature: 0.7
          max-tokens: 5000

    google:
      genai:
        embedding:
          api-key: ${API_KEY}
          project-id: ${PROJECT_ID}
          text:
            options:
              model: gemini-embedding-001
              dimensions: 768
        chat:
          enabled: false
#    ollama:
#      base-url: http://localhost:11434
#      init:
#        timeout: 5m
#      chat:
#        options:
#          model: qwen3:4b
#      embedding:
#        options:
#          model: qwen3-embedding:0.6b
#          dimensions: 1024

    mcp:
      client:
        enabled: true
        initialized: true
        request-timeout: 120s
        streamable-http:
          connections:
            ms-checkpoint:
              url: ${URL_MCP_SSE_CHECKPOINT}
              endpoint: /checkpoint/mcp

  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DATABASE}


server:
  port: ${PORT}
  servlet:
    context-path: /ai-engine

semantic:
  cache:
    redis:
      host: ${REDIS_CACHE_HOST}
      port: ${REDIS_CACHE_PORT}
      user: ${REDIS_CACHE_USER}
      password: ${REDIS_CACHE_PASSWORD}
    similarity-threshold: 0.95
    ttl-seconds: 3600

logging:
  level:
    org.springframework.ai.mcp: DEBUG
    io.modelcontextprotocol: DEBUG
    org.springframework.web.reactive.function.client: DEBUG

cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}