spring.application.name=ms-ai-engine
server.port=8081
server.servlet.context-path=/ai-engine

# Configuracion de Spring AI para Claude (Chat)
spring.ai.anthropic.api-key=${ANTHROPIC_API_KEY}
spring.ai.anthropic.chat.options.model=claude-sonnet-4-5
spring.ai.anthropic.chat.options.temperature=0.7
spring.ai.anthropic.chat.options.max-tokens=5000

# Configuracion de Spring AI para Google GenAI (Embedding)
spring.ai.google.genai.embedding.api-key=${API_KEY}
spring.ai.google.genai.embedding.project-id=${PROJECT_ID}
spring.ai.google.genai.embedding.text.options.model=gemini-embedding-001
spring.ai.google.genai.embedding.text.options.dimensions=768

#MCP Configuracion de Spring AI para MCP
spring.ai.mcp.cliente.enable=true
spring.ai.mcp.cliente.initializated=true
spring.ai.mcp.cliente.request-timeout=60s

spring.ai.mcp.client.stremeable-http.connections.github-mcp.url=https://api.githubcopilot.com/mcp/
spring.ai.mcp.client.stremeable-http.connections.github-mcp.authorization:=Bearer ${GITHUB_MCP_TOKEN}

# Postgres datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/ai_engine
spring.datasource.username=ai_engine
spring.datasource.password=ai_engine
spring.datasource.driver-class-name=org.postgresql.Driver

# Spring AI PgVector
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.table-name=ai_embeddings
spring.ai.vectorstore.pgvector.dimensions=768
spring.ai.vectorstore.pgvector.distance-type=cosine_distance
spring.ai.vectorstore.pgvector.id-type=TEXT
