spring.application.name=ms-ai-engine

# Configuracion de Spring AI para Google GenAI
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-pro
spring.ai.google.genai.embedding.options.model=text-embedding-004
