spring.application.name=ms-ai-engine

# Configuracion de Spring AI para Google GenAI
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-pro
spring.ai.google.genai.embedding.options.model=text-embedding-004

# Postgres datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/ai_engine
spring.datasource.username=ai_engine
spring.datasource.password=ai_engine
spring.datasource.driver-class-name=org.postgresql.Driver

# Spring AI PgVector
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.table-name=ai_embeddings
spring.ai.vectorstore.pgvector.dimensions=768
spring.ai.vectorstore.pgvector.distance-type=cosine_distance

